apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops-demo
  template:
    metadata:
      labels:
        app: devsecops-demo
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: devsecops-demo
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
